variables:
  DOCKER_IMAGE: robocop-backend
  DOCKER_TAG: ${CI_COMMIT_SHA}

stages:
  - build
  - deploy

build:
  stage: build
  only:
    - develop
  script:
    - docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} .
    - docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKER_IMAGE}:latest

deploy:
  stage: deploy
  only:
    - develop
  script:
    - curl -X POST http://jenkins서버:8080/job/robocop-backend-deploy/build \
      --user ${JENKINS_USER}:${JENKINS_TOKEN} 