version: '3'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env  # 환경변수 파일 사용
    volumes:
      - ./app:/BACKEND_WAS/app  # 로컬의 app 폴더를 컨테이너와 연결
    # mongodb 서비스는 필요없으므로 제거 