pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE = 'robocop-backend'
        DOCKER_TAG = "${env.BUILD_NUMBER}"
        EC2_HOST = '13.124.XX.XX'  // EC2 퍼블릭 IP
        EC2_USER = 'ubuntu'
    }
    
    stages {
        stage('Prepare Backend') {
            steps {
                dir('BACKEND_WAS') {
                    sh 'chmod +x deploy/deploy.sh'
                }
            }
        }
        
        stage('Deploy to EC2') {
            steps {
                sshagent(['EC2_SSH_KEY']) {
                    sh """
                        ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} 'mkdir -p ~/robocop'
                        scp -r BACKEND_WAS/* ${EC2_USER}@${EC2_HOST}:/home/${EC2_USER}/robocop/
                        
                        ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} '''
                            cd ~/robocop
                            ./deploy/deploy.sh
                        '''
                    """
                }
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
    }
} 