#
#@brief 2D 포즈 배열로 목표 지점을 나타냅니다.
#
#이 배열은 여러 목표 지점을 포함하며, 각 목표 지점은 2D 포즈로 표현됩니다.
#각 Pose2D는 다음과 같이 구성됩니다:
#- x: 목표 지점의 x 좌표.
#- y: 목표 지점의 y 좌표.
#- theta: 목표 지점의 방향(라디안 단위).
#
#이는 로봇이 여러 웨이포인트에 도달해야 하는 내비게이션 작업에 주로 사용됩니다.
#
geometry_msgs/Pose2D[] goals
---
bool success
string message
